name: sparse_sensing
channels:
  - pytorch
dependencies:
  - python=3.6
  - cudatoolkit=10.2
  - pip
  - pip:
    - torch==1.5.1
    - torchvision==0.6.1
    - epic-kitchens==1.7.0
    - librosa==0.7.0
    - numba==0.45.1
    - llvmlite==0.32.1
    - cupy-cuda102==7.6.0
    - nose2
    - pyyaml
    - opencv-python
    - pandas
    - scikit-image
    - natsort
    - seaborn
    - tensorboard
