model_name: 'Pipeline4'
model_params:
    feat_model_cfg:   'configs/model_cfgs/ucf101/san19_multi_pairwise_224_actnetpretrained.yaml'
    actreg_model_cfg: 'configs/model_cfgs/ucf101/actreggru2.yaml'
    using_cupy: False
    num_class: 101
    num_segments: 16
    modality: ['RGB']
    dropout: 0.5
    new_length:
        RGB: 1
