model_name: 'SANMulti'
model_params:
    san_sa_type: 0  # Pairwise
    san_layers:  [3, 3, 4, 6, 3]
    san_kernels: [3, 7, 7, 7, 7]
    san_pretrained_weights: 
        RGB: 'pretrained/ucf101/san19_224/rgb.model'
