batch_size: 48
num_workers: 20
n_epochs: 15
lr_steps: [5, 10]  # Epochs to decay learning rate by 10
print_freq: 20  # Print frequency
clip_gradient: 20.0  # Gradient norm clipping. Default = None
partialbn: True
freeze: True  # freeze the feature extraction model
eval_freq: 1
optimizer: 'Adam'
optim_params:
    lr: 0.0003
