batch_size: 128
num_workers: 20
n_epochs: 100
lr_steps: [30, 60, 90]  # Epochs to decay learning rate by 10
print_freq: 20  # Print frequency
clip_gradient: 20.0  # Gradient norm clipping. Default = None
partialbn: False
freeze: False  # freeze all weights except fusion
eval_freq: 1
optimizer: 'SGD'
optim_params:
    lr: 0.01
    momentum: 0.9
    weight_decay: 1.e-4
